baseURL = 'https://ugurkoysuren.com'
languageCode = "en-us"
title = "Ugur Köysüren's Blog, Blogging about Tech"

theme = "paperesque"

# Dummy code
# We're building drafts in config so that you can see them in the example on
# Hugo Themes; you almost certainly don't want this on your production site
buildDrafts = false

[markup]
# This is the default from Hugo 0.60.0 onwards, but we're setting config
# for it below, so make it explicit
defaultMarkdownHandler = "goldmark"

# Required to render HTML tags in the hugoExampleSite examples.
[markup.goldmark.renderer]
unsafe = true

# I can't remember if this is required for syntax highlighting or not.
pygmentsUseClasses = true

# Uncomment these lines for droplist / resource removal support! See the
# README for more details

# [outputs]
# page = ["HTML", "droplist"]

[params]
# Turn this on if you want to disable margin notes everywhere!
# disableMarginNotes = true
Author = 'Ugur Köysüren'
Keywords = [
    "Ugur Köysüren",
    "Software",
    "Programming",
    "Developer",
    "Personal Blog",
    "Programming Blog",
    "Docker",
    "Hugo",
    "Selfhosted"
]

description = 'Ugur Köysüren - Senior Consultant, Developer, Overthinker, Blogger'

# Customise your home page menu here:



# And your top-right menu links here.

[[params.topmenu]]
name = "about"
url = "about"
[[params.topmenu]]
name = "posts"
url = "posts"

[[params.topmenu]]
name = "tags"
url = "tags"

[[params.topmenu]]
name = "rss"
url = "posts/index.xml"